fits:
  - labcore.analysis.fitfuncs.generic.Cosine
  - labcore.analysis.fitfuncs.generic.Exponential
  - labcore.analysis.fitfuncs.generic.ExponentialDecay
  - labcore.analysis.fitfuncs.generic.ExponentiallyDecayingSine